# Generated by Django 3.1.1 on 2020-10-15 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slag',
            new_name='slug',
        ),
    ]
